name = "gandalf-collector"
main = "src/collector.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/5 * * * *"]  # Every 5 minutes

[[kv_namespaces]]
binding = "MARKET_CACHE"
id = "fdb7c06916734e528b4d37a963a52a04"