name = "gandalf-analyzer"
main = "src/analyzer.js"
compatibility_date = "2024-01-01"
account_id = "19d25279bc9bed348875d2f840c48588"  # THIS IS THE CORRECT ONE

[triggers]
crons = ["*/15 * * * *"]  # Every 15 minutes for testing

[[kv_namespaces]]
binding = "PATTERN_CACHE"
id = "a20a59448ed343be8b13f98a2b1b0031"  # This is the KV namespace ID (correct)