name = "gandalf-collector"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/5 * * * *"]  # Every 5 minutes

[[kv_namespaces]]
binding = "MARKET_CACHE"
id = "fdb7c06916734e528b4d37a963a52a04"

[vars]
SUPABASE_URL = "https://noovgylllgdyxylnqbux.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vb3ZneWxsbGdkeXh5bG5xYnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTc4MTMsImV4cCI6MjA3MTM5MzgxM30.qFUArh7c0BvsueTjzpu_NLZESRAeqIho3k64iQV0fSc"