name = "gandalf-analyzer"
main = "src/analyzer.js"
compatibility_date = "2024-01-01"
account_id = "19d25279bc9bed348875d2f840c48588"

[triggers]
crons = ["*/15 * * * *"]

[[kv_namespaces]]
binding = "PATTERN_CACHE"
id = "a20a59448ed343be8b13f98a2b1b0031"