name: Strategy Backtest (Weekly)

on:
  schedule: [ { cron: '0 6 * * 1' } ]  # Mon 06:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  backtest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup
      - name: Run Backtest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: python scripts/backtest_strategy.py
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: backtest-results-${{ github.run_id }}
          path: output/
          retention-days: 30