name: Strategy Backtest

on:
  schedule:
    - cron: '0 6 * * 1'  # Weekly Monday 06:00 UTC
  workflow_dispatch:

jobs:
  backtest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install deps
        run: |
          pip install pandas==2.3.2 numpy==2.2.6 requests==2.32.5
      - name: Run Backtest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: python scripts/backtest_strategy.py
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: backtest-results-${{ github.run_id }}
          path: output/
          retention-days: 30