name: Deep Market Analysis

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  analyze-and-store:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run analysis
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: python scripts/deep_analysis.py
      - name: Store results
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: python scripts/store_results.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: analysis-results-${{ github.run_id }}
          path: output/
          retention-days: 30