name: Discover Liquid Items
on:
  schedule:
    - cron: '0 1 * * 0' # Sunday 01:00 UTC
  workflow_dispatch:

concurrency:
  group: discover-liquidity-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install deps
        run: pip install aiohttp==3.9.5 requests==2.32.5
      - name: Run discovery
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: python scripts/discover_liquid_items.py