name: Discover Liquid Items (Weekly)

on:
  schedule: [ { cron: '0 1 * * 0' } ]  # Sun 01:00 UTC
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: discover-liquidity-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup
      - name: Run discovery
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: python scripts/discover_liquid_items.py