name: ML Inference (Hourly)

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  infer:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: ml-inference-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unified inference
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          PRED_HORIZON_STEPS: "6"
          BLEND_WEIGHT: "0.7"
        run: python scripts/infer_unified.py