name: ML Model Training (Weekly)

on:
  schedule:
    - cron: '0 2 * * 0' # Sun 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ml-training-${{ github.ref }}
  cancel-in-progress: true

jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Train unified model
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          TRAIN_DAYS: '30'
          CV_SPLITS: '3'
          SEARCH_ITER: '20'
        run: python scripts/train_unified_model.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-models-${{ github.run_id }}
          path: models/
          retention-days: 30
      - name: Commit updated models
        shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if compgen -G "models/*.pkl" > /dev/null; then
            git add models/*.pkl models/*.json || true
            if ! git diff --staged --quiet; then
              git commit -m "chore(models): update unified ML model [skip ci]"
              git push
            else
              echo "No model changes."
            fi
          else
            echo "No model files to commit."
          fi