name: ML Model Training

on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM
  workflow_dispatch:

jobs:
  train-models:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install pandas numpy scikit-learn requests joblib
    
    - name: Train ML models
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python scripts/train_models.py
    
    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ml-models
        path: models/
        retention-days: 30
    
    - name: Commit models (optional)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add models/*.pkl models/*.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update ML models [skip ci]"
        git push || echo "No changes to push"