# FINAL & FIXED ml-training.yml
name: ML Model Training

on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM
  workflow_dispatch:

jobs:
  train-models:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: 1. Checkout Repository
      uses: actions/checkout@v4
    
    - name: 2. Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: 3. Install Dependencies
      run: |
        pip install pandas numpy scikit-learn requests joblib
    
    - name: 4. Train ML models
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python scripts/train_models.py
    
    - name: 5. Upload model artifacts
      uses: actions/upload-artifact@v4 # FIXED
      with:
        name: ml-models-${{ github.run_id }}
        path: models/
        retention-days: 30
    
    - name: 6. Commit models (Optional)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add models/*.pkl models/*.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update ML models [skip ci]"
        git push || echo "No changes to commit"