name: Monitor System Health

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check-health:
    runs-on: ubuntu-latest
    steps:
      - name: Check Worker Health
        run: |
          curl -s https://gandalf-collector.${{ secrets.WORKER_SUBDOMAIN }}.workers.dev/health || true
      - name: Check Data Freshness (API health)
        run: echo "Add API endpoint checks here if needed"