name: Refresh Tracked Items (Daily)

on:
  schedule: [ { cron: '0 3 * * *' } ]  # daily 03:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup
      - name: Refresh (Top 50)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: python scripts/refresh_tracked_items.py