name: Score Predictions

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  score:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install deps
        run: |
          pip install requests==2.32.5 python-dateutil==2.9.0.post0
      - name: Score predictions (30m horizon)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          PREDICTION_HORIZON_MIN: "30"
        run: python scripts/score_predictions.py